name: Run Tests
on:
    workflow_call:
    push:
        paths:
            - 'tests/**'
            - 'src/**'
            - 'jest.config.ts'
            - 'package.json'
            - 'tsconfig.json'

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
              - name: Checkout
                uses: actions/checkout@v3

              - name: Setup Node
                uses: actions/setup-node@v3
                with:
                    node-version: latest

              - name: Install Dependencies
                run: npm i

              - name: Run Tests
                run: npm run test

              - name: Check Types
                run: npm run type-check

